---
- name: Example of lineinfile
  hosts: dns_servers
  vars:
    success: false

  tasks:

    - name: get time

      shell: /usr/bin/date
      register: var_time
    - name: get time serial format

      shell: /usr/bin/date +%Y%m%M%S
      register: var_time_sec

    - name: "Example1: Validate if a String or line is present in the file"
      become: yes
      become_user: mario
      tags: example1
      lineinfile:
        path: /home/mario/Build/db.test
        regexp: ".ps3."
        state: absent
        backup: yes
      checkmode: yes
    set_fact:
      success: true
      
    - name: "update serial bind for propagation"
      lineinfile:
        dest: '/home/mario/Build/db.test'
        regexp: '.Serial\s'
        line: "\t\t\t\t\t\t{{ var_time_sec.stdout }}\t\t;\tSerial"
        state: 'present'
      when: success