---
- name: Delete entry from DNS
  hosts: all
  vars:
    success: false
  vars_files:
    - ./extra_vars_dns.yml

  tasks:

    - name: get time

      shell: /usr/bin/date
      register: var_time
    - name: get time serial format

      shell: /usr/bin/date +%Y%m%M%S
      register: var_time_sec

    - name: backup current dns zone file
      become: true
      copy:
        remote_src: yes
        src: "{{ path_dns_file }}"
        dest: "{{ path_dns_file }}.{{ var_time_sec.stdout }}"
      register: backup_file

    - name: debug backup
      debug:
        msg: 
        - "-----------------backup file--------------"
        - " {{ backup_file.dest }} "
        - "------------------------------------------"

    - name: "locate fqdn and delete if needed"
      become: true
      tags: example1
      lineinfile:
        path: '{{ path_dns_file }}'
        regexp: "{{ subdomain }}( |\t)"
        state: absent
      register: delete_fqdn
      
    - name: "update serial bind for propagation"
      become: true
      lineinfile:
        dest: "{{ path_dns_file}}"
        regexp: '.(S|s)erial\s'
        line: "\t\t\t{{ var_time_sec.stdout }}\t; Serial"
        state: 'present'
      when: delete_fqdn.changed

    - name: result add dns entries to named zones
    
      debug:
        msg: 
          - "--------------------------------------------------------------"
          - " Execution time:   {{ var_time.stdout }}"
          - " Updated Serial parameter to:    {{ var_time_sec.stdout }}"
          - " Deleted entry:    {{ subdomain }} "
          - "--------------------------------------------------------------"
        
      when: delete_fqdn.changed