---
- name: Add entries from DNS
  hosts: all
  vars:
    success: false
  vars_files:
    - ./extra_vars_dns.yml

  tasks:
    - name: get time

      shell: /usr/bin/date
      register: var_time
    - name: get time serial format

      shell: /usr/bin/date +%Y%m%M%S
      register: var_time_sec

    - name: "try to locate fqdn and add it if not exist"
      become: yes
      become_user: mario
      tags: example1
      lineinfile:
        path: /home/mario/Build/db.test
        regexp: "{{ subdomain }}"
        line: "{{ subdomain }}\t\t\tIN\t{{ dns_type }}\t{{ ip_address }}"
        state: present
        backup: yes
        insertafter: "ORIGIN {{ domain }}."
      #checkmode: yes
      register: add_fqdn
      
    - name: "update serial bind for propagation"
      lineinfile:
        dest: '/home/mario/Build/db.test'
        regexp: '.Serial\s'
        line: "\t\t{{ var_time_sec.stdout }}\t; Serial"
        state: 'present'
      when: add_fqdn.changed

    - name: result add dns entries to named zones
    
      debug:
        msg:
          - "--------------------------------------------------------------"
          - " Execution time:   {{ var_time.stdout }}"
          - " Updated Serial parameter to:    {{ var_time_sec.stdout }}"
          - " Added entry:    {{ subdomain }}      IN  {{ dns_type }} {{ ip_address }}"
          - " Backup File generated:    {{ add_fqdn.backup }}"
          - "--------------------------------------------------------------"
      when: add_fqdn.changed