---
- name: Modify multiple type entries to DNS
  hosts: all
  vars:
    success: false
  vars_files:
    - ./extra_vars_dns_mod.yml

  tasks:
  - name: get time

    shell: /usr/bin/date
    register: var_time
  - name: get time serial format

    shell: /usr/bin/date +%Y%m%M%S
    register: var_time_sec
  
  - name: backup current dns zone file
    become: true
    copy:
      remote_src: yes
      src: "{{ path_dns_file }}"
      dest: "{{ path_dns_file }}.{{ var_time_sec.stdout }}"
    register: backup_file

  - name: debug backup
    debug:
      msg: 
      - "-----------------backup file--------------"
      - " {{ backup_file.dest }} "
      - "------------------------------------------"

  - name: Modify Registers types
    include_tasks: dns-bind-mod.yml
    loop: "{{ registers_type }}"
    loop_control:
      loop_var: register
    register: add_fqdn
      
  - name: "update serial bind for propagation"
    become: true
    become_user: root
    become_method: su
    lineinfile:
      dest: '{{ path_dns_file }}'
      regexp: '.(S|s)erial\s'
      line: "                                {{ var_time_sec.stdout }} ; serial"
      state: 'present'
    when: add_fqdn.changed
