---
- name: Delete entry from DNS
  hosts: all
  vars:
    success: false
  vars_files:
    - ./extra_vars_dns.yml

  tasks:

    - name: get time

      shell: /usr/bin/date
      register: var_time
    - name: get time serial format

      shell: /usr/bin/date +%Y%m%M%S
      register: var_time_sec

    - name: "locate fqdn and delete if needed"
      become: yes
      become_user: mario
      tags: example1
      lineinfile:
        path: '{{ path_dns_file }}'
        regexp: "{{ subdomain }}( |\t)"
        state: absent
        backup: yes
      #checkmode: yes
      register: delete_fqdn
      
    - name: "update serial bind for propagation"
      lineinfile:
        dest: "{{ path_dns_file}}"
        regexp: '.(S|s)erial\s'
        line: "\t\t\t{{ var_time_sec.stdout }}\t; Serial"
        state: 'present'
      when: delete_fqdn.changed

    - name: result add dns entries to named zones
    
      debug:
        msg: 
          - "--------------------------------------------------------------"
          - " Execution time:   {{ var_time.stdout }}"
          - " Updated Serial parameter to:    {{ var_time_sec.stdout }}"
          - " Deleted entry:    {{ subdomain }}      IN  {{ dns_type }} {{ ip_address }}"
          - " Backup File generated:    {{ delete_fqdn.backup }}"
          - "--------------------------------------------------------------"
        
      when: delete_fqdn.changed