---
- hosts: all
  tasks:
    - name: get time serial format

      shell: /usr/bin/date +%Y%m%M%S
      register: var_time_sec


    - name: Make sure test file exists
      file:
        dest: './example-tab.txt'
        state: 'touch'
      changed_when: False

    - name: Add a line with Tabs
      lineinfile:
        dest: './example-tab.txt'
        regexp: '.Serial\s'
        line: "\t\t\t\t\t\t{{ var_time_sec.stdout }}\t\t;\tSerial"
        state: 'present'

  #  - name: Ensure line with Tabs is present
  #    lineinfile:
  #      dest: './example-tab.txt'
  #      regexp: '^First\s'
  #      line: "First\tSecond\tThird"
  #      state: 'present'
